version = 0.1

[default.deploy.parameters]
stack_name = "mail-sender"
resolve_s3 = true
s3_prefix = "mail-sender"
region = "sa-east-1"
profile = "<perfil-aws>"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "SesFrom=\"<remetente-verificado@example.com>\""
